const fs = require('fs');

const en = {
  nav: {
    home: "Home",
    services: "Services",
    portfolio: "Portfolio",
    about_us: "About Us",
    blog: "Blog",
    contact: "Contact Us",
    lets_talk: "Let's Talk",
    english: "English",
    indonesia: "Indonesia"
  },
  hero: {
    badge: "Software Engineering & Problem Solving",
    heading: "We build software that solves real business challenges.",
    subtext: "HaenSoftware is a premier software development agency. We blend engineering excellence with a problem-solving mindset to deliver scalable, custom digital solutions that drive measurable business impact.",
    cta_primary: "Start a Project",
    cta_secondary: "View Our Work"
  },
  dashboard: {
    overview: "Overview",
    analytics: "Analytics",
    projects: "Projects",
    users: "Users",
    billing: "Billing",
    settings: "Settings",
    performance: "Performance",
    revenue: "Revenue",
    recent_activity: "Recent Activity",
    activity_registered: "New user registered",
    activity_payment: "Payment received",
    activity_subscription: "Subscription updated",
    activity_report: "Report generated",
    system_stability: "System Stability",
    uptime: "Uptime",
    ago: "h ago"
  },
  services_section: {
    badge: "Our Expertise",
    heading: "Engineering solutions for complex problems.",
    subtext: "We go beyond just writing code. We act as your strategic technical partner to dissect business bottlenecks and deliver robust, scalable technology that fuels long-term growth.",
    custom_software_title: "Custom Software Engineering",
    custom_software_desc": "Tailor-made web, mobile, and desktop applications architected specifically for your unique operational needs.",
    problem_solving_title: "Strategic Problem Solving",
    problem_solving_desc": "We analyze complex workflow inefficiencies and design effective, highly scalable digital solutions.",
    cloud_devops_title": "Cloud Architecture & DevOps",
    cloud_devops_desc": "Resilient cloud infrastructure design, seamless DevOps automation, and scalable server management.",
    product_development_title": "Product Scaling & MVP",
    product_development_desc": "Rapid MVP development, continuous product evolution, and technical scaling for sustainable business growth."
  },
  approach_section: {
    badge: "Our Methodology",
    heading: "How we turn complexity into elegant solutions.",
    subtext: "A proven, systematic software engineering approach that ensures high-quality deliverables, seamless scalability, and strict alignment with your strategic business objectives.",
    discover_label: "Discovery",
    discover_desc": "We conduct deep-dive analyses to thoroughly understand your business domain, user demographics, and core challenges.",
    define_label": "Definition",
    define_desc": "We articulate the precise problem statement and validate the proposed technical approach before writing a single line of code.",
    develop_label": "Development",
    develop_desc": "We engineer robust, scalable solutions utilizing clean code principles, automated testing, and modern development practices.",
    deliver_label": "Delivery & Evolution",
    deliver_desc": "We deploy the solution, measure its operational impact, and continuously iterate to ensure long-term, sustainable success."
  },
  portfolio_section: {
    badge: "Proven Impact",
    heading": "Projects that deliver tangible value.",
    subtext: "We don't just deliver software—we deliver solutions to complex business bottlenecks. Explore some of the high-impact systems we've engineered.",
    cta: "Ready to accelerate your business?",
    cta_subtext": "Let's discuss how we can architect a technical solution that drives measurable, scalable growth for your organization.",
    view_case_study: "Read Full Case Study"
  },
  portfolio_page: {
    hero_heading_1": "Real problems.",
    hero_heading_2": "Real impact.",
    hero_subtext": "Explore our portfolio of custom software implementations. We engineer robust systems that drive operational efficiency, seamless scalability, and measurable business growth.",
    our_work: "Our Work",
    cta_heading: "Want results like these?",
    cta_subtext": "Tell us about your technical challenges. We'll map out a clear, strategic path to a solution that delivers immediate and lasting impact.",
    start_project: "Start Your Project",
    haen_komputer_title: "Haen Komputer Management System",
    haen_komputer_desc": "We transformed Haen Komputer's fragmented, spreadsheet-based operations into a fully integrated, custom ERP system powered by the TALL Stack. This solution drastically reduced manual errors and provided real-time operational visibility across procurement, sales, inventory management, and financial accounting.",
    haen_komputer_short_desc": "A complete digital transformation from manual retail operations to a unified, custom ERP system.",
    tag_retail: "Retail",
    outcome_efficiency: "40% efficiency gain"
  },
  case_study: {
    client: "Client",
    industry: "Industry",
    timeline: "Timeline",
    team: "Team",
    year: "Year",
    outcome: "Outcome",
    the_client: "The Client",
    the_idea: "The Vision",
    the_challenge: "The Challenge",
    the_result: "The Result",
    business_challenge: "The Business Challenge",
    architecture: "System Architecture",
    product_tour: "Product Tour",
    development_timeline: "Development Timeline",
    tech_stack: "Technology Stack",
    impact_results: "Impact & Results",
    client_testimonial: "Client Testimonial"
  },
  haen_komputer_case_study: {
    client_desc: "Haen Komputer is a custom PC building service dedicated to helping users create machines tailored perfectly to their needs. In a market saturated with one-size-fits-all prebuilt systems, they offer flexible component customization and expert technical guidance, allowing customers to build high-performance, personalized systems without compromise.",
    the_idea: "The vision was to elevate Haen Komputer's traditional, spreadsheet-dependent workflow into a modern, fully integrated digital ecosystem. This system needed to streamline daily operations, eliminate manual calculation errors, and boost overall efficiency, all while maintaining an intuitive user interface for staff with varying levels of technical expertise.",
    the_challenge: "Their legacy workflow relied heavily on disconnected spreadsheets and manual accounting, often utilizing physical calculators for critical transactions. Over eight years, these fragmented and highly unconventional methods became deeply entrenched in their daily routines, making it nearly impossible to standardize processes or seamlessly transition to an off-the-shelf ERP solution.",
    the_result: "We delivered a fully bespoke ERP system tailored specifically to Haen Komputer's unique operational model. This transformation replaced years of fragmented, manual processes with a cohesive, centralized digital workflow. The new system accelerated daily operations, removed the dependency on manual calculations, and established a scalable technical foundation for their future expansion.",
    business_challenge_intro: "Haen Komputer's operational capabilities were severely bottlenecked by fragmented and manual workflows. Their accounting records lacked consistency, tracking transactions was a complex and time-consuming ordeal, and critical inventory processes—such as stock mutations and physical audits—were unreliable. Consequently, the management team faced significant hurdles in maintaining accurate data and exerting operational control.",
    problem_1: "Accounting processes relied entirely on manually updated spreadsheets, creating a critical dependency on specific staff members and leading to glaring gaps in financial records whenever updates were inevitably missed.",
    problem_2: "Transaction tracking was highly fragmented. Purchase and sales activities were often recorded informally through WhatsApp groups, rendering data exceedingly difficult to trace, validate, and consolidate for reporting.",
    problem_3: "An overreliance on informal communication channels resulted in scattered, unstructured documentation and severely reduced overall operational visibility.",
    problem_4: "Inventory management lacked robust tracking mechanisms. Crucial events like stock movements and warranty return processes went unrecorded, leading to highly inconsistent and unreliable stock data.",
    problem_5: "Service and repair items were not consistently logged within the system, causing frequent miscommunications and coordination breakdowns between technical staff.",
    highlight_1_title: "Manual Accounting Dependency",
    highlight_1_desc: "Financial record-keeping relied on fragile spreadsheets, creating data gaps and heavy reliance on the availability of specific personnel.",
    highlight_2_title: "Fragmented Tracking",
    highlight_2_desc: "Critical purchase and sales records were scattered across informal chat applications, severely impeding transaction traceability and validation.",
    highlight_3_title: "Inventory Blind Spots",
    highlight_3_desc: "The absence of proper tracking for stock movements and warranty returns resulted in highly unreliable inventory data.",
    highlight_4_title: "Unstructured Workflows",
    highlight_4_desc: "Inconsistent recording of operational tasks and service items led to widespread miscommunication and inefficient team coordination.",
    architecture_intro: "We architected the system around Haen Komputer's core business domains: Sales, Procurement, Inventory, Service, and Accounting. Each isolated domain was unified into a centralized platform, enabling instantaneous data synchronization across transactions, stock movements, and financial ledgers. This holistic approach guarantees consistent data flow and unparalleled operational visibility across all departments.",
    feature_1_title: "Procurement & Purchasing",
    feature_1_item_1: "Purchase Order Management: End-to-end lifecycle tracking for supplier purchase orders.",
    feature_1_item_2: "Finalized Data Protection: Implemented immutable edit locks on historical purchase data (PO details, items, grand totals) to guarantee absolute data integrity.",
    feature_1_item_3: "Supplier Management: A centralized database for tracking vendor information and historical performance metrics.",
    feature_1_item_4: "Purchasing Reports: Granular, automated reporting on procurement activities and aggregate expenses.",
    feature_2_title: "Sales & Point of Sale",
    feature_2_item_1: "POS System: A specialized, high-speed interface optimized for direct retail sales and seamless transaction processing.",
    feature_2_item_2: "Tukar Tambah (Trade-in): Engineered complex logic to handle multifaceted product trade-ins natively within the standard sales flow.",
    feature_2_item_3: "Member Management: Comprehensive customer database for tracking loyalty and purchasing history.",
    feature_2_item_4: "Sales Reporting: Dynamic dashboards providing deep insights into sales performance and revenue generation.",
    feature_3_title: "Inventory & Warehouse Management",
    feature_3_item_1: "Unified Inventory: Real-time, synchronized stock tracking across multiple physical warehouse locations (Gudang).",
    feature_3_item_2: "Stock Adjustment & Opname: Specialized tools for manual stock corrections and streamlined periodic physical inventory audits.",
    feature_3_item_3: "Product Catalog: Robust management of products, SKUs, brands, and hierarchical categories.",
    feature_3_item_4: "Batch Tracking Logic: Advanced stock management utilizing unique batch identifiers for pinpoint inventory precision and warranty tracking.",
    feature_4_title: "Human Resources & Finance",
    feature_4_item_1: "Attendance (Absensi): Digital employee check-in/out and comprehensive attendance tracking.",
    feature_4_item_2: "Payroll (Gaji Karyawan): Automated salary calculations and secure payroll management.",
    feature_4_item_3: "Leave Management: Streamlined reporting and automated approval workflows for employee leave requests.",
    feature_4_item_4: "Accounting Integration: A fully mapped Chart of Accounts (Kode Akun) ensuring automated transaction mapping for complete financial transparency.",
    feature_5_title: "System Integrity & Support",
    feature_5_item_1: "Validation Logs: An internal auditing system designed for tracking and resolving operational and data discrepancies.",
    feature_5_item_2: "Role-Based Access Control (RBAC): Granular security restrictions (e.g., isolating Validation Log resolution exclusively to Manager roles).",
    feature_5_item_3: "RMA (Return Merchandise Authorization): A dedicated module for handling complex product returns and warranty claims.",
    feature_5_item_4: "Notification System: Real-time, system-wide alerts for critical operational events and required approvals.",
    feature_6_title: "Database Optimization",
    feature_6_item_1: "Seeder Cleanup: Streamlined database initialization architecture, retaining only essential master data seeders (Karyawan and Kode Akun) for rapid deployments.",
    timeline_1_title: "Discovery Phase",
    timeline_1_desc: "Stakeholder Requirements: We identified the critical need for a unified system bridging retail operations (POS), inventory, and backend accounting. Problem Identification: Pinpointed major pain points including inventory leakage, compromised purchasing data integrity, and the necessity for granular approval workflows. Scope Definition: Defined core modules (Purchasing, Sales, Inventory, HR, Accounting). Tech Stack Selection: Chose the TALL Stack (Tailwind CSS, Alpine.js, Laravel, Livewire) with FilamentPHP to guarantee rapid development alongside a premium, custom user experience.",
    timeline_2_title: "UI/UX Design",
    timeline_2_desc: "Information Architecture: Logically structured complex business data into intuitive Resources and Relation Managers, drastically reducing user cognitive load. Admin-First Experience: Customized Filament's design system for a clean, consistent interface, particularly optimizing complex multi-step forms like Trade-ins (Tukar Tambah). Aesthetic Polish: Delivered a modern, dark-mode friendly UI with high-contrast elements vital for high-speed retail environments. Responsiveness: Ensured full mobile responsiveness, allowing managers to approve logs on the go while retail staff utilize tablets and desktops.",
    timeline_3_title: "Development",
    timeline_3_desc: "Backend Architecture: Leveraged Laravel 11 with Service Classes and Action patterns to decouple complex business logic (e.g., batch inventory calculation) from the UI layer. Feature Implementation: Developed immutable historical edit locks to freeze financial records. Managed deep, complex relationships between Products, Brands, and multi-warehouse Inventory. Security & RBAC: Enforced strict Role-Based Access Control via Laravel Policies to isolate sensitive operations. Database Design: Engineered optimized MySQL schemas with strategic indexing to handle massive datasets in real-time reporting.",
    timeline_4_title: "Testing",
    timeline_4_desc: "Functional Testing: Executed comprehensive end-to-end testing of the Order-to-Stock flow, ensuring purchases accurately update both warehouse inventory and accounting ledgers simultaneously. Integrity Verification: Utilized the custom Validation Log system as an automated auditing tool to trap anomalies during the beta phase. User Acceptance Testing (UAT): Simulated high-pressure retail scenarios (sales returns, stock audits) to validate UI resilience. Role Validation: Rigorously audited permission matrices to guarantee staff cannot bypass security protocols or access sensitive payroll data.",
    timeline_5_title: "Deployment",
    timeline_5_desc: "Containerization: Implemented Podman/Docker to establish a highly reproducible environment, guaranteeing absolute consistency from development to production. Environment Orchestration: Secured configurations via robust .env structures and maximized production performance using Laravel's native caching mechanisms. Migration Strategy: Authored streamlined deployment pipelines handling database migrations and essential master data seeding while preserving production data integrity. CI/CD Ready: Architected the codebase for seamless automated deployment pipelines, enabling zero-downtime iterations.",
    results_efficiency: "Efficiency Gain",
    results_paper: "Paper Reduction",
    results_accuracy: "Data Accuracy",
    results_report: "Report Accuracy",
    results_paper_val: "Significant",
    results_accuracy_val: "Real-time",
    results_report_suffix: "% increase",
    testimonial_quote: "Before the implementation of this custom system, our daily closing process was an absolute nightmare. We were heavily reliant on a massive, unstable Excel sheet that crashed frequently, and we routinely discovered 'invisible' financial losses simply because someone forgot to update a formula or manual stock count. Transitioning to this unified platform changed everything for us. The most monumental win is the automated Batch and Serial Number tracking. Now, when a customer initiates a warranty claim, we can retrieve the exact purchase date and Serial Number in a matter of seconds. There is no more digging through archived physical receipts or navigating endless Excel tabs. This system alone has saved our team at least 15 hours of tedious, manual administrative work every single week!",
    testimonial_name: "Operations Manager",
    testimonial_role: "Operations Lead",
    testimonial_company: "Haen Komputer"
  },
  contact_page: {
    hero_heading_1: "Let's build something",
    hero_heading_2: "extraordinary",
    hero_heading_3: "together.",
    subtext: "Do you have a complex technical challenge? Or simply want to explore how custom software can scale your business? We'd love to connect and strategize.",
    contact_us: "Contact Us",
    contact_email_desc: "For general inquiries, RFPs, and project consultations.",
    contact_phone_desc: "For immediate assistance and direct technical discussions.",
    working_hours: "Operating Hours",
    working_days: "Monday - Saturday",
    working_time: "9:00 AM - 5:00 PM (WIB)",
    working_desc: "Our engineering and support teams are available for consultations.",
    visit_us: "Visit Our Headquarters",
    visit_desc: "Our primary engineering hub located in Central Java, Indonesia."
  },
  cta_section: {
    badge: "Let's Collaborate",
    heading_1: "Ready to engineer something",
    heading_2: "that matters?",
    subtext: "Share your business challenge with us. We will bring technical clarity, select the optimal tech stack, and assign an engineering team that is deeply invested in your success.",
    start_project: "Start a Project",
    view_work: "Explore Our Work",
    trust_shield: "No long-term vendor lock-in",
    trust_clock: "Guaranteed response within 24h",
    trust_star: "Trusted by 30+ forward-thinking companies"
  },
  footer: {
    description: "Architecting software solutions that generate tangible business impact through pristine code, highly scalable infrastructure, and a profound understanding of your unique operational bottlenecks.",
    services: "Expertise",
    custom_software: "Custom Software",
    problem_solving: "Strategic Consulting",
    cloud_devops: "Cloud & DevOps",
    product_development: "Product Engineering",
    company: "Company",
    about_us: "About Us",
    case_studies: "Case Studies",
    blog: "Technical Blog",
    contact: "Get in Touch",
    all_rights_reserved: "All rights reserved.",
    privacy_policy: "Privacy Policy",
    terms_of_service: "Terms of Service",
    cookie_policy: "Cookie Policy"
  }
};

const id = {
  nav: {
    home: "Beranda",
    services: "Layanan",
    portfolio: "Portofolio",
    about_us: "Tentang Kami",
    blog: "Blog",
    contact: "Hubungi Kami",
    lets_talk: "Mari Berdiskusi",
    english: "English",
    indonesia: "Indonesia"
  },
  hero: {
    badge: "Pengembangan Software & Problem Solving",
    heading: "Kami membangun software untuk menyelesaikan tantangan bisnis.",
    subtext: "HaenSoftware adalah software development agency yang membangun solusi digital kustom untuk membantu bisnis bekerja lebih efisien, scalable, dan berdampak nyata.",
    cta_primary: "Mulai Proyek",
    cta_secondary: "Lihat Karya Kami"
  },
  dashboard: {
    overview: "Ikhtisar",
    analytics: "Analitik",
    projects: "Proyek",
    users: "Pengguna",
    billing: "Tagihan",
    settings: "Pengaturan",
    performance: "Performa",
    revenue: "Pendapatan",
    recent_activity: "Aktivitas Terbaru",
    activity_registered: "Pengguna baru terdaftar",
    activity_payment: "Pembayaran diterima",
    activity_subscription: "Langganan diperbarui",
    activity_report: "Laporan dibuat",
    system_stability: "Stabilitas Sistem",
    uptime: "Waktu Aktif",
    ago: "j lalu"
  },
  services_section: {
    badge: "Keahlian Kami",
    heading: "Solusi rekayasa untuk mengatasi masalah yang kompleks.",
    subtext: "Kami tidak sekadar menulis kode. Kami bertindak sebagai mitra strategis Anda untuk membedah masalah operasional dan menghadirkan teknologi yang tangguh serta skalabel guna mendorong pertumbuhan jangka panjang.",
    custom_software_title: "Pengembangan Software Kustom",
    custom_software_desc: "Aplikasi web, mobile, dan desktop yang dirancang dan diarsiteki khusus untuk memenuhi kebutuhan operasional unik bisnis Anda.",
    problem_solving_title: "Pemecahan Masalah Strategis",
    problem_solving_desc: "Kami menganalisis inefisiensi alur kerja yang kompleks dan merancang solusi digital yang efektif, praktis, dan sangat skalabel.",
    cloud_devops_title: "Arsitektur Cloud & DevOps",
    cloud_devops_desc: "Desain infrastruktur cloud yang tangguh, otomatisasi DevOps yang mulus, dan manajemen server berskala besar.",
    product_development_title": "Pengembangan & Skalabilitas Produk",
    product_development_desc: "Pengembangan MVP yang cepat, evolusi produk berkelanjutan, dan skalabilitas teknis untuk pertumbuhan bisnis yang berkesinambungan."
  },
  approach_section: {
    badge: "Metodologi Kami",
    heading: "Bagaimana kami mengubah kerumitan menjadi solusi elegan.",
    subtext: "Pendekatan rekayasa software yang sistematis dan teruji untuk menjamin hasil berkualitas tinggi, skalabilitas tanpa hambatan, dan keselarasan penuh dengan tujuan strategis bisnis Anda.",
    discover_label: "Eksplorasi Mendalam",
    discover_desc: "Kami melakukan analisis mendalam untuk memahami secara menyeluruh domain bisnis Anda, demografi pengguna, dan akar permasalahan utama.",
    define_label": "Perumusan Strategi",
    define_desc: "Kami merumuskan pernyataan masalah secara presisi dan memvalidasi pendekatan teknis yang diusulkan sebelum menulis satu baris kode pun.",
    develop_label": "Pengembangan Sistem",
    develop_desc: "Kami merekayasa solusi yang tangguh dan skalabel menggunakan prinsip kode bersih, pengujian otomatis, dan praktik pengembangan modern.",
    deliver_label": "Peluncuran & Evolusi",
    deliver_desc: "Kami menerapkan solusi, mengukur dampak operasionalnya, dan terus melakukan iterasi untuk memastikan kesuksesan jangka panjang yang berkelanjutan."
  },
  portfolio_section: {
    badge: "Dampak Terbukti",
    heading: "Proyek yang memberikan nilai nyata.",
    subtext: "Kami tidak sekadar menyerahkan software—kami memberikan solusi untuk hambatan bisnis yang kompleks. Jelajahi beberapa sistem berdampak tinggi yang telah kami bangun.",
    cta: "Siap mengakselerasi bisnis Anda?",
    cta_subtext: "Mari berdiskusi tentang bagaimana kami dapat merancang solusi teknis yang mendorong pertumbuhan terukur dan skalabel bagi organisasi Anda.",
    view_case_study: "Baca Studi Kasus Lengkap"
  },
  portfolio_page: {
    hero_heading_1: "Masalah nyata.",
    hero_heading_2: "Dampak nyata.",
    hero_subtext: "Jelajahi portofolio implementasi software kustom kami. Kami merekayasa sistem tangguh yang mendorong efisiensi operasional, skalabilitas mulus, dan pertumbuhan bisnis yang terukur.",
    our_work: "Karya Kami",
    cta_heading: "Menginginkan hasil seperti ini?",
    cta_subtext: "Ceritakan tantangan teknis Anda. Kami akan memetakan jalur strategis yang jelas menuju solusi yang memberikan dampak langsung dan jangka panjang.",
    start_project: "Mulai Proyek Anda",
    haen_komputer_title: "Sistem Manajemen Haen Komputer",
    haen_komputer_desc: "Kami mengubah operasional Haen Komputer yang terfragmentasi dan berbasis spreadsheet menjadi sistem ERP kustom yang terintegrasi penuh, didukung oleh TALL Stack. Solusi ini secara drastis mengurangi kesalahan manual dan memberikan visibilitas operasional real-time di seluruh manajemen pengadaan, penjualan, inventaris, dan akuntansi keuangan.",
    haen_komputer_short_desc: "Transformasi digital menyeluruh dari operasional ritel manual menjadi sistem ERP kustom yang terpadu.",
    tag_retail: "Ritel",
    outcome_efficiency: "Peningkatan efisiensi sebesar 40%"
  },
  case_study: {
    client: "Klien",
    industry: "Industri",
    timeline: "Durasi Proyek",
    team: "Tim",
    year: "Tahun",
    outcome: "Hasil",
    the_client: "Klien Kami",
    the_idea: "Visi Proyek",
    the_challenge: "Tantangan Utama",
    the_result: "Hasil Akhir",
    business_challenge: "Tantangan Bisnis",
    architecture: "Arsitektur Sistem",
    product_tour: "Tur Produk",
    development_timeline: "Lini Masa Pengembangan",
    tech_stack: "Teknologi yang Digunakan",
    impact_results: "Dampak & Hasil",
    client_testimonial: "Testimoni Klien"
  },
  haen_komputer_case_study: {
    client_desc: "Haen Komputer adalah layanan perakitan PC kustom yang berdedikasi membantu pengguna menciptakan mesin yang disesuaikan secara sempurna dengan kebutuhan mereka. Di pasar yang dipenuhi dengan sistem prebuilt generik, mereka menawarkan kustomisasi komponen yang fleksibel dan panduan teknis ahli, memungkinkan pelanggan membangun sistem personal berkinerja tinggi tanpa kompromi.",
    the_idea: "Visinya adalah untuk meningkatkan alur kerja tradisional Haen Komputer yang bergantung pada spreadsheet menjadi ekosistem digital modern yang terintegrasi penuh. Sistem ini diperlukan untuk merampingkan operasi harian, mengeliminasi kesalahan perhitungan manual, dan meningkatkan efisiensi secara keseluruhan, sekaligus mempertahankan antarmuka pengguna yang intuitif bagi staf dengan berbagai tingkat keahlian teknis.",
    the_challenge: "Alur kerja lama mereka sangat bergantung pada spreadsheet yang tidak saling terhubung dan akuntansi manual, sering kali menggunakan kalkulator fisik untuk transaksi penting. Selama delapan tahun, metode yang terfragmentasi dan sangat tidak konvensional ini menjadi sangat mendarah daging dalam rutinitas harian mereka, sehingga hampir mustahil untuk menstandarkan proses atau beralih ke solusi ERP siap pakai.",
    the_result: "Kami memberikan sistem ERP yang sepenuhnya dirancang khusus yang disesuaikan dengan model operasional unik Haen Komputer. Transformasi ini menggantikan proses manual yang terfragmentasi selama bertahun-tahun dengan alur kerja digital yang kohesif dan terpusat. Sistem baru ini mempercepat operasi harian, menghilangkan ketergantungan pada perhitungan manual, dan membangun fondasi teknis yang skalabel untuk ekspansi mereka di masa depan.",
    business_challenge_intro: "Kemampuan operasional Haen Komputer sangat terhambat oleh alur kerja manual yang terfragmentasi. Catatan akuntansi mereka tidak konsisten, pelacakan transaksi adalah cobaan yang rumit dan memakan waktu, dan proses inventaris kritis—seperti mutasi stok dan audit fisik—tidak dapat diandalkan. Akibatnya, tim manajemen menghadapi kendala besar dalam mempertahankan data yang akurat dan menjalankan kendali operasional.",
    problem_1: "Proses akuntansi sepenuhnya bergantung pada spreadsheet yang diperbarui secara manual, menciptakan ketergantungan kritis pada anggota staf tertentu dan menyebabkan celah yang mencolok dalam catatan keuangan setiap kali pembaruan tidak terhindarkan terlewatkan.",
    problem_2: "Pelacakan transaksi sangat terfragmentasi. Aktivitas pembelian dan penjualan sering dicatat secara informal melalui grup WhatsApp, membuat data sangat sulit untuk dilacak, divalidasi, dan dikonsolidasikan untuk pelaporan.",
    problem_3: "Ketergantungan yang berlebihan pada saluran komunikasi informal menghasilkan dokumentasi yang tidak terstruktur dan tersebar, dan sangat mengurangi visibilitas operasional secara keseluruhan.",
    problem_4: "Manajemen inventaris tidak memiliki mekanisme pelacakan yang kuat. Peristiwa penting seperti pergerakan stok dan proses pengembalian garansi tidak tercatat, yang mengarah pada data stok yang sangat tidak konsisten dan tidak dapat diandalkan.",
    problem_5: "Barang servis dan perbaikan tidak dicatat secara konsisten di dalam sistem, menyebabkan miskomunikasi yang sering terjadi dan gangguan koordinasi di antara staf teknis.",
    highlight_1_title: "Ketergantungan Akuntansi Manual",
    highlight_1_desc: "Pencatatan keuangan bergantung pada spreadsheet yang rentan, menciptakan celah data dan ketergantungan besar pada ketersediaan personel tertentu.",
    highlight_2_title: "Pelacakan Terfragmentasi",
    highlight_2_desc: "Catatan pembelian dan penjualan penting tersebar di aplikasi obrolan informal, sangat menghambat ketertelusuran dan validasi transaksi.",
    highlight_3_title: "Titik Buta Inventaris",
    highlight_3_desc: "Tidak adanya pelacakan yang tepat untuk pergerakan stok dan pengembalian garansi menghasilkan data inventaris yang sangat tidak dapat diandalkan.",
    highlight_4_title: "Alur Kerja Tidak Terstruktur",
    highlight_4_desc: "Pencatatan tugas operasional dan barang servis yang tidak konsisten menyebabkan miskomunikasi yang meluas dan koordinasi tim yang tidak efisien.",
    architecture_intro: "Kami merancang arsitektur sistem di sekitar domain bisnis inti Haen Komputer: Penjualan, Pengadaan, Inventaris, Servis, dan Akuntansi. Setiap domain yang terisolasi disatukan ke dalam platform terpusat, memungkinkan sinkronisasi data seketika di seluruh transaksi, pergerakan stok, dan buku besar keuangan. Pendekatan holistik ini menjamin aliran data yang konsisten dan visibilitas operasional yang tak tertandingi di semua departemen.",
    feature_1_title: "Pengadaan & Pembelian",
    feature_1_item_1: "Manajemen Pesanan Pembelian: Pelacakan siklus hidup end-to-end untuk pesanan pembelian pemasok.",
    feature_1_item_2: "Perlindungan Data Final: Menerapkan kunci edit yang tidak dapat diubah pada data pembelian historis (detail PO, item, total keseluruhan) untuk menjamin integritas data absolut.",
    feature_1_item_3: "Manajemen Pemasok: Database terpusat untuk melacak informasi vendor dan metrik kinerja historis.",
    feature_1_item_4: "Laporan Pembelian: Pelaporan terperinci dan otomatis tentang aktivitas pengadaan dan pengeluaran agregat.",
    feature_2_title: "Penjualan & Point of Sale",
    feature_2_item_1: "Sistem POS: Antarmuka berkecepatan tinggi yang dikhususkan, dioptimalkan untuk penjualan ritel langsung dan pemrosesan transaksi yang mulus.",
    feature_2_item_2: "Tukar Tambah (Trade-in): Merancang logika kompleks untuk menangani tukar tambah produk multifaset secara native dalam alur penjualan standar.",
    feature_2_item_3: "Manajemen Anggota: Database pelanggan komprehensif untuk melacak loyalitas dan riwayat pembelian.",
    feature_2_item_4: "Pelaporan Penjualan: Dasbor dinamis yang memberikan wawasan mendalam tentang kinerja penjualan dan perolehan pendapatan.",
    feature_3_title: "Manajemen Inventaris & Gudang",
    feature_3_item_1: "Inventaris Terpadu: Pelacakan stok real-time yang disinkronkan di berbagai lokasi gudang fisik.",
    feature_3_item_2: "Penyesuaian Stok & Opname: Alat khusus untuk koreksi stok manual dan audit inventaris fisik berkala yang efisien.",
    feature_3_item_3: "Katalog Produk: Manajemen yang kuat untuk produk, SKU, merek, dan kategori hierarkis.",
    feature_3_item_4: "Logika Pelacakan Batch: Manajemen stok lanjutan yang menggunakan pengidentifikasi batch unik untuk presisi inventaris dan pelacakan garansi.",
    feature_4_title: "Sumber Daya Manusia & Keuangan",
    feature_4_item_1: "Kehadiran (Absensi): Check-in/out karyawan digital dan pelacakan kehadiran komprehensif.",
    feature_4_item_2: "Penggajian (Gaji Karyawan): Perhitungan gaji otomatis dan manajemen penggajian yang aman.",
    feature_4_item_3: "Manajemen Cuti: Pelaporan yang efisien dan alur kerja persetujuan otomatis untuk permintaan cuti karyawan.",
    feature_4_item_4: "Integrasi Akuntansi: Bagan Akun (Kode Akun) yang dipetakan sepenuhnya memastikan pemetaan transaksi otomatis untuk transparansi keuangan yang lengkap.",
    feature_5_title: "Integritas & Dukungan Sistem",
    feature_5_item_1: "Log Validasi: Sistem audit internal yang dirancang untuk melacak dan menyelesaikan perbedaan operasional dan data.",
    feature_5_item_2: "Role-Based Access Control (RBAC): Pembatasan keamanan terperinci (misalnya, mengisolasi resolusi Log Validasi secara eksklusif untuk peran Manajer).",
    feature_5_item_3: "RMA (Return Merchandise Authorization): Modul khusus untuk menangani pengembalian produk yang kompleks dan klaim garansi.",
    feature_5_item_4: "Sistem Pemberitahuan: Peringatan real-time di seluruh sistem untuk peristiwa operasional penting dan persetujuan yang diperlukan.",
    feature_6_title: "Optimasi Database",
    feature_6_item_1: "Pembersihan Seeder: Arsitektur inisialisasi database yang efisien, hanya mempertahankan seeder data master esensial (Karyawan dan Kode Akun) untuk penerapan yang cepat.",
    timeline_1_title: "Fase Eksplorasi",
    timeline_1_desc: "Persyaratan Pemangku Kepentingan: Kami mengidentifikasi kebutuhan kritis untuk sistem terpadu yang menjembatani operasi ritel (POS), inventaris, dan akuntansi backend. Identifikasi Masalah: Menentukan titik kelemahan utama termasuk kebocoran inventaris, integritas data pembelian yang terganggu, dan kebutuhan akan alur kerja persetujuan yang terperinci. Definisi Ruang Lingkup: Mendefinisikan modul inti (Pembelian, Penjualan, Inventaris, SDM, Akuntansi). Pemilihan Tech Stack: Memilih TALL Stack (Tailwind CSS, Alpine.js, Laravel, Livewire) dengan FilamentPHP untuk menjamin pengembangan yang cepat bersama dengan pengalaman pengguna kustom yang premium.",
    timeline_2_title: "Desain UI/UX",
    timeline_2_desc: "Arsitektur Informasi: Menyusun data bisnis yang kompleks secara logis ke dalam Resource dan Relation Manager yang intuitif, secara drastis mengurangi beban kognitif pengguna. Pengalaman Mengutamakan Admin: Menyesuaikan sistem desain Filament untuk antarmuka yang bersih dan konsisten, khususnya mengoptimalkan formulir multi-langkah yang kompleks seperti Tukar Tambah. Pemolesan Estetika: Memberikan UI modern yang ramah mode gelap dengan elemen kontras tinggi yang vital untuk lingkungan ritel berkecepatan tinggi. Responsivitas: Memastikan responsivitas seluler penuh, memungkinkan manajer menyetujui log saat bepergian sementara staf ritel menggunakan tablet dan desktop.",
    timeline_3_title: "Pengembangan",
    timeline_3_desc: "Arsitektur Backend: Memanfaatkan Laravel 11 dengan pola Service Class dan Action untuk memisahkan logika bisnis yang kompleks (misalnya, perhitungan inventaris batch) dari lapisan UI. Implementasi Fitur: Mengembangkan kunci edit historis yang tidak dapat diubah untuk membekukan catatan keuangan. Mengelola hubungan yang dalam dan kompleks antara Produk, Merek, dan Inventaris multi-gudang. Keamanan & RBAC: Menegakkan Role-Based Access Control yang ketat melalui Laravel Policy untuk mengisolasi operasi sensitif. Desain Database: Merancang skema MySQL yang dioptimalkan dengan pengindeksan strategis untuk menangani kumpulan data masif dalam pelaporan real-time.",
    timeline_4_title: "Pengujian",
    timeline_4_desc: "Pengujian Fungsional: Melakukan pengujian end-to-end komprehensif dari alur Order-to-Stock, memastikan pembelian secara akurat memperbarui inventaris gudang dan buku besar akuntansi secara bersamaan. Verifikasi Integritas: Memanfaatkan sistem Log Validasi kustom sebagai alat audit otomatis untuk menjebak anomali selama fase beta. Pengujian Penerimaan Pengguna (UAT): Mensimulasikan skenario ritel bertekanan tinggi (pengembalian penjualan, audit stok) untuk memvalidasi ketahanan UI. Validasi Peran: Mengaudit matriks izin secara ketat untuk menjamin staf tidak dapat melewati protokol keamanan atau mengakses data penggajian yang sensitif.",
    timeline_5_title: "Penerapan",
    timeline_5_desc: "Kontainerisasi: Menerapkan Podman/Docker untuk membangun lingkungan yang sangat dapat direproduksi, menjamin konsistensi mutlak dari pengembangan hingga produksi. Orkestrasi Lingkungan: Mengamankan konfigurasi melalui struktur .env yang kuat dan memaksimalkan kinerja produksi menggunakan mekanisme caching bawaan Laravel. Strategi Migrasi: Menyusun alur penerapan yang efisien untuk menangani migrasi database dan penyemaian data master esensial sambil menjaga integritas data produksi. Siap CI/CD: Merancang basis kode untuk alur penerapan otomatis yang mulus, memungkinkan iterasi tanpa waktu henti.",
    results_efficiency: "Peningkatan Efisiensi",
    results_paper: "Pengurangan Kertas",
    results_accuracy: "Akurasi Data",
    results_report: "Akurasi Laporan",
    results_paper_val: "Signifikan",
    results_accuracy_val: "Seketika",
    results_report_suffix: "% peningkatan",
    testimonial_quote: "Sebelum implementasi sistem kustom ini, proses penutupan harian kami benar-benar merupakan mimpi buruk. Kami sangat bergantung pada lembar Excel masif dan tidak stabil yang sering crash, dan kami secara rutin menemukan kerugian finansial 'tak terlihat' hanya karena seseorang lupa memperbarui rumus atau jumlah stok manual. Beralih ke platform terpadu ini mengubah segalanya bagi kami. Kemenangan paling monumental adalah pelacakan Batch dan Nomor Seri otomatis. Sekarang, ketika pelanggan mengajukan klaim garansi, kami dapat mengambil tanggal pembelian dan Nomor Seri yang tepat dalam hitungan detik. Tidak ada lagi menggali melalui kuitansi fisik yang diarsipkan atau menavigasi tab Excel tanpa akhir. Sistem ini sendiri telah menghemat setidaknya 15 jam kerja administratif manual yang membosankan dari tim kami setiap minggunya!",
    testimonial_name: "Operations Manager",
    testimonial_role: "Operations Lead",
    testimonial_company: "Haen Komputer"
  },
  contact_page: {
    hero_heading_1: "Mari membangun sesuatu yang",
    hero_heading_2: "luar biasa",
    hero_heading_3: "bersama-sama.",
    subtext: "Apakah Anda memiliki tantangan teknis yang kompleks? Atau sekadar ingin mendiskusikan bagaimana software kustom dapat menskalakan bisnis Anda? Kami siap terhubung dan merancang strategi.",
    contact_us: "Hubungi Kami",
    contact_email_desc: "Untuk pertanyaan umum, RFP, dan konsultasi proyek.",
    contact_phone_desc: "Untuk bantuan segera dan diskusi teknis langsung.",
    working_hours: "Jam Operasional",
    working_days: "Senin - Sabtu",
    working_time: "09:00 - 17:00 (WIB)",
    working_desc: "Tim rekayasa dan dukungan kami tersedia untuk konsultasi.",
    visit_us: "Kunjungi Kantor Pusat Kami",
    visit_desc: "Pusat rekayasa utama kami berlokasi di Jawa Tengah, Indonesia."
  },
  cta_section: {
    badge: "Mari Berkolaborasi",
    heading_1: "Siap merekayasa sesuatu yang",
    heading_2: "berdampak besar?",
    subtext: "Bagikan tantangan bisnis Anda kepada kami. Kami akan memberikan kejelasan teknis, memilih tech stack yang optimal, dan menugaskan tim rekayasa yang sangat berdedikasi pada kesuksesan Anda.",
    start_project: "Mulai Proyek",
    view_work: "Eksplorasi Karya Kami",
    trust_shield: "Tanpa ikatan kontrak jangka panjang yang merugikan",
    trust_clock: "Jaminan respons dalam 24 jam",
    trust_star: "Dipercaya oleh 30+ perusahaan inovatif"
  },
  footer: {
    description: "Merancang arsitektur solusi software yang menghasilkan dampak bisnis nyata melalui kode yang bersih, infrastruktur yang sangat skalabel, dan pemahaman mendalam tentang hambatan operasional unik Anda.",
    services: "Keahlian",
    custom_software: "Software Kustom",
    problem_solving: "Konsultasi Strategis",
    cloud_devops: "Cloud & DevOps",
    product_development: "Rekayasa Produk",
    company: "Perusahaan",
    about_us: "Tentang Kami",
    case_studies: "Studi Kasus",
    blog: "Blog Teknis",
    contact: "Hubungi Kami",
    all_rights_reserved: "Hak cipta dilindungi undang-undang.",
    privacy_policy: "Kebijakan Privasi",
    terms_of_service: "Ketentuan Layanan",
    cookie_policy: "Kebijakan Cookie"
  }
};

fs.writeFileSync('en.lang', JSON.stringify(en, null, 2));
fs.writeFileSync('id.lang', JSON.stringify(id, null, 2));
console.log("Language files updated.");
